### ISSUE TITLE
Faster response from API

### ISSUE THREAD

**Issue by mpagels** [mpagels/collectoPod#1]
## Value statement - a requirement, not a solution
As a **user** 
I need **faster response from the api** 
so that **I don't have to wait to long to get the data** 

## Description (Text, Scribble, Wireframe, Design)
- no visible change for the user

## Acceptance criteria
- [ ] after start of website, the api data is fast loaded and available

## Tasks
- [x] set up a mongoDB database
- [x] put all exisiting data in database
- [ ] send data from database to frontend
- [x] logic for check if new content available, put it in databse
- [ ] add a "cronjob" to scrap new data every day at 0 o'clock

## Size
(large)
