### ISSUE TITLE
Logging function in scrapper.py

### ISSUE THREAD

**Issue by mpagels** [mpagels/collectoPod#14]
## Value statement - a requirement, not a solution
As a **admin** 
I need **a logger function for scrapper.py** 
so that **I can see all logging information, when the script is invoked through pm2/cron** 

## Description (Text, Scribble, Wireframe, Design)
In production, pm2 handles the executing of scrapper.py. so if someting goes wrong through the hole scrapp process I need a log file, to see exactly what went wrong, to do better debugging. Especially when I came back to the project months later.

## Acceptance criteria
- [x] log INFO when scrapper.py is executed
~~- [ ] log INFO when request with podcast url is started~~
- [x] log INFO how much new entries went to collection
- [x] log ERROR if request goes wrong
- [x] log ERROR if database connection went wrong
- [x] log ERROR if collection insert went wrong
- [x] if there was an error while executing, send a telegram message with an url entpoint to the logfile

## Tasks
- [x] create endpoint for /api/logger

## Size
(large)

**Comment by mpagels** [comment]
place this here for later: 
https://stackoverflow.com/questions/36090655/running-a-python-script-in-virtual-environment-with-node-js-pm2
