### ISSUE TITLE
Podcast activate/deactivate function

### ISSUE THREAD

**Issue by mpagels** [mpagels/collectoPod#21]
## Value statement - a requirement, not a solution
As an **user** 
I need **the possibility to activate or deactivate podcasts** 
so that **I can deactivate current unuses podcasts, that will not be displayed** 

## Acceptance criteria
- [x] I see a list of podcasts
- [ ] When untick the podcast list item, the listitem will be greyed out
- [ ] When I tick the podcast list item, the listitem will be back to normal
- [ ] When I hit the save button, the settings will be saved
- [ ] and the podcast will be displayed/not displayes in their category, depending on the setting

## Tasks
)

## Size
(large)
