### ISSUE TITLE
Podcast "store" feature

### ISSUE THREAD

**Issue by mpagels** [mpagels/collectoPod#26]
## Value statement - a requirement, not a solution
As a **user** 
I need **a store where I can see all available podcasts** 
so that **I can choose my favorite podcasts and save it in or remove it from my profile**

## Description (Text, Scribble, Wireframe, Design)
![Untitled-2020-12-15-0036(1)](https://user-images.githubusercontent.com/54703643/102622547-7c5bc200-4141-11eb-9246-21f8af10ca2b.png)

## Acceptance criteria
- [ ] all available podcasts from DB are shown with the podcasts logos (small) in a list
- [ ] on the top left above the podcast logo is the "back to store" button, if this is clicked, i get back to the homepage
- [ ] already saved podcasts are shown with a little green tick on the right bottom on top of the podcast logo
- [ ] when I click on a podcast logo, the podcast information site will be opened
--
- [ ] there I can see the podcast logo in big
- [ ] on the top left above the podcast logo is the "back to store" button, if this is clicked, i get back to the store 
- [ ] the description text what the podcast is about
- [ ] the action button shows "add to account" or "remove from account", depending podcast is already in account or not
--
- [ ] when hit "add to account" a pop up is shown, with the question
- [ ] to close the pop-up, and abort the save process, I can hit the X in the right top corner
- [ ] I can choose the category from a top down list
- [ ] or I can choose to add a new category
- [ ] if new category is selected, a input field is shown, where the user can input the new category
- [ ] when hit the save button, the app checks, if category still exists, and shows an error, that category exists and to choose another category name
- [ ] if category not exists, the app saves the podcast to that category and closes the popup and reloads the podcast overview site

## Tasks
- [ ] make small "store" podcast-logos

## Size
(large)
